version: '3'
services:
  laugh_vue_app:
    container_name: laugh_vue
    command: /bin/bash -c "cd laugh/ && npm install && npm run dev"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./laugh_vue
        target: /laugh_vue
    tty: true
    ports:
    - "3000:3000"