version: '3'
services:
  vue_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./vue
        target: /vue
    tty: true
    ports:
    - "3000:3000"